### ISSUE TITLE
Unable to import this npm package in my existing vuejs web application

### ISSUE THREAD

**Issue by ravijayaraman** [iobroker-community-adapters/ioBroker.mydlink#106]
**Describe the bug**  
index.js?df7c:117 Uncaught TypeError: Arguments to path.join must be strings
    at eval (index.js?df7c:117)
    at Array.filter (<anonymous>)
    at filter (index.js?df7c:287)
    at Object.exports.join (index.js?df7c:115)
    at Object.eval (utils.js?3a9b:50)
    at eval (utils.js:54)
    at Object../node_modules/@iobroker/adapter-core/build/utils.js (chunk-vendors.js:23)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (index.js?9508:7)
eval @ index.js?df7c:117
filter @ index.js?df7c:287
exports.join @ index.js?df7c:115
eval @ utils.js?3a9b:50
eval @ utils.js:54
./node_modules/@iobroker/adapter-core/build/utils.js @ chunk-vendors.js:23
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ index.js?9508:7
./node_modules/@iobroker/adapter-core/build/index.js @ chunk-vendors.js:11
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ main.js?fe4e:19
eval @ main.js:1193
./node_modules/iobroker.mydlink/main.js @ chunk-vendors.js:3072
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ Rules.vue?752d:55
./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Rules.vue?vue&type=script&lang=js& @ app.js:985
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ Rules.vue?2df7:1
./src/views/Rules.vue?vue&type=script&lang=js& @ app.js:1304
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ Rules.vue?7d6c:1
./src/views/Rules.vue @ app.js:1292
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ router.js?41cb:1
./src/router.js @ app.js:1280
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ main.js:14
./src/main.js @ app.js:1268
__webpack_require__ @ app.js:849
fn @ app.js:151
0 @ app.js:1414
__webpack_require__ @ app.js:849
checkDeferredModules @ app.js:46
(anonymous) @ app.js:925
(anonymous) @ app.js:928
Show 12 more frames
vue.runtime.esm.js?2b0e:8434 

**To Reproduce**  
1. Installed the package through "npm i iobroker.mydlink"
2. const DlinkSmarthome = require("iobroker.mydlink"); in the .vue file where I want to use
3. The error is shown  Uncaught TypeError: Arguments to path.join must be strings

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 1.1.7
 - Node version: <node-version> v12.18.4
 - Operating system: <os-name> Mac OS Catalina 10.15.7 (19H15)

**Comment by Garfonso** [comment]
Js Controller version is much too old.
What are you trying to do? Do you know what IoBroker is?

If you do not want to work with IoBroker but something else, have a look at https://github.com/Garfonso/dlinkWebSocketClient
