### ISSUE TITLE
Adapter wird nicht grün

### ISSUE THREAD

**Issue by hotwin** [iobroker-community-adapters/ioBroker.mydlink#11]
bei mir bleibt der adapter gelb
https://i.gyazo.com/0cef85ff3342a79826bf50430a77e3f4.png
https://gyazo.com/b887e4c37e1768e74032da9266a13608

**Comment by Garfonso** [comment]
Hi,

gelb heißt, es gibt keine Verbindung zu einem Gerät.
Bei deiner Konfig ist hinten "enable" nicht aktiviert -> das heißt das Gerät wird nicht genutzt (ist dafür gedacht, dass man Geräte nur temporär nutzt, z.B. eine Steckdose für die Weihnachtsdeko und dann nicht im ganzen Sommer Fehler im Log hat, weil die nicht erreichbar ist -> mit einem Haken kann man die da an/abstellen). Insofern gibt es aktuell kein Gerät für den Adapter. Ok, da müsste er dann nicht gelb werden. Hm. Muss ich mal gucken, ob ich den Fall abfange.

Egal, kurz: Mach mal den Haken bei enable rein und guck, ob es dann geht. Falls nicht, bitte mal ein debug log vom Adapter start posten (am besten aus der console).
