### ISSUE TITLE
Activate Buttons does not work

### ISSUE THREAD

**Issue by unstressable** [iobroker-community-adapters/ioBroker.mydlink#49]
The Activate Buttons in iobroker Adapter went always to active, even when I click inactive.

Theres no possibility to save it.
Just close and reopen the settings to see it.

![image](https://user-images.githubusercontent.com/50423935/95360291-7a68bd80-08cb-11eb-98e5-4cbb978f777a.png)

**Comment by Garfonso** [comment]
I can not reproduce this issue. Steps:

- open config
- disable one / two / three of three devices
- press "save & exit"
- adapter restarts, won't talk to disabled devices, "enabled" objects turn to false, 'active' stays unchecked.

what did you do and see exactly?

**Comment by unstressable** [comment]
I did it exactly the same way.

-Open config
-Disabled 2 of 3
-save and exit
-back to config and all 3 have been activated

**Comment by unstressable** [comment]
Problem solved with the latest version 1.1.7

**Comment by unstressable** [comment]
solved
